#
#功能：实现 异常捕捉和错误截图
#

# Generated by Selenium IDE
import time
import unittest
import os
import sys
import re
from selenium import webdriver
from selenium.webdriver.common.by import By

class Test080301(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

# 测试用例必须以test开头
    def test_1(self):
        driver = self.driver
        driver.get("https://www.baidu.com/")
        driver.maximize_window()
        driver.find_element(By.ID, "kw").send_keys("乘风破浪的姐姐")
        driver.find_element(By.ID, "su").click()
        time.sleep(5)
        try:
            print("==================")
            print(driver.title)
            self.assertEqual(u"12345上网从这里开始", driver.title)
        except:
            self.saveScreenShot(driver, "hao.png")
            time.sleep(4)

    # 截图创建
    def saveScreenShot(self, driver, file_name):
            if not os.path.exists("./errorImageFile"):
                os.makedirs("./errorImageFile")
            now = time.strftime("%Y%m%d-%H%M%S", time.localtime(time.time()))
            print(now)
            driver.get_screenshot_as_file("./errorImageFile/"+now+"-"+file_name)# 截图命名并保存
            time.sleep(3)

