# Generated by Selenium IDE
import time
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By


class Test080302(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    # @unittest.skip("skipping")
    def test_2(self):
        self.driver.get("https://www.baidu.com/")
        self.driver.set_window_size(932, 659)
        self.driver.find_element(By.ID, "kw").send_keys("二十不惑")
        self.driver.find_element(By.ID, "su").click()
        time.sleep(2)
        self.assertEqual("123", "123", msg="两个不相等") #添加断言，判断实际结果和预期结果是否一致，验证测试用例结果是否正确
        self.assertFalse("111" == "111", msg="条件正确")
        time.sleep(2)

    def test_3(self):
        self.driver.get("https://www.baidu.com/")
        self.driver.set_window_size(932, 659)
        self.driver.find_element(By.ID, "kw").send_keys("三十而已")
        self.driver.find_element(By.ID, "su").click()
        time.sleep(2)