# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
# import pytest
# import unittest

class TestUntitled():
  def setup_method(self, method):
    # self.driver = webdriver.Firefox()
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("http://localhost:8080/ses/public/index.html")
    time.sleep(2)
    self.driver.set_window_size(932, 661)
    time.sleep(5)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("abc")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, "#login_form .btn-success").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main_fail_modal_dialog span").click()
    self.driver.find_element(By.ID, "exam_tab").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main_fail_modal_dialog span").click()
    self.driver.find_element(By.ID, "exam_record_tab").click()
    element = self.driver.find_element(By.ID, "exam_record_tab")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.NAME, "btSelectItem").click()
  
# #必须加上main方法，不然运行没有反应
# if __name__ == '__main__':
#     unittest.main()